clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
matrix:
  include:
    - image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
      platform: linux/amd64
      monero_make: monero_linux_amd64
      moneroc_make: moneroc_linux_host64
      prepare_cmd: echo ok
      prepare_cmd_depends: echo ok
      triplet: x86_64-linux-gnu
    - image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
      platform: linux/aarch64
      monero_make: monero_linux_arm64
      moneroc_make: moneroc_linux_host64
      prepare_cmd: echo ok
      prepare_cmd_depends: echo ok
      triplet: aarch64-linux-gnu
    - image: git.mrcyjanek.net/mrcyjanek/sailfishos:4.5.0.18_aarch64
      platform: linux/aarch64
      monero_make: monero_linux_arm64
      moneroc_make: moneroc_linux_host64
      prepare_cmd: zypper in -y git clang libxkbcommon-devel wayland-protocols-devel wayland-client wayland-egl-devel make glibc-static
      prepare_cmd_depends: make host_tool_perl
      triplet: aarch64-linux-sailfishos

labels:
  platform: ${platform}

steps:
  - name: clone repositories
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make download
  - name: build depends
    image: ${image}
    commands:
      - ${prepare_cmd}
      - ${prepare_cmd_depends}
      - make libiconv_host
      - make boost_host
      - make zlib_host
      - make openssl_host
      - make openssl_host_alt
      - make libzmq_host
      - make libsodium_host
      - make host_copy_libs
      - make libexpat_host
      - make unbound_host
      - make polyseed_host
      - make utf8proc_host
      - make host_copy_libs
      - make ${monero_make}
  - name: build ${moneroc_make}
    image: ${image}
    commands:
      - ${prepare_cmd}
      - make ${moneroc_make}
  - name: info
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - ls -lah libbridge/build/libwallet2_api_c.so
      - file libbridge/build/libwallet2_api_c.so
      - md5sum libbridge/build/libwallet2_api_c.so
      - sha256sum libbridge/build/libwallet2_api_c.so
      - sha512sum libbridge/build/libwallet2_api_c.so
  - name: upload artifact
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - rm -rf ~/.ssh || true
      - mkdir -p ~/.ssh
      - echo "$${SSH_PRIVKEY}" > ~/.ssh/id_rsa
      - chmod 700 ~/.ssh
      - chmod 600 ~/.ssh/id_rsa
      - xz -e libbridge/build/libwallet2_api_c.so
      - rsync --mkpath -e "ssh -o StrictHostKeyChecking=no" -raz libbridge/build/libwallet2_api_c.so.xz $${SSH_HOST}:"$${SSH_BASE_PATH}/$(git describe --tags)/$${triplet}_libwallet2_api_c.so.xz"
    secrets: [ ssh_privkey, ssh_host, ssh_base_path ]