clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
matrix:
  include:
    # - image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    #   platform: linux/amd64
    #   make_steps: depends_host monero_linux_amd64 moneroc_linux_host64
    #   prepare_cmd: echo ok
    #   prepare_cmd_depends: echo ok
    #   triplet: x86_64-linux-gnu
    #   cc: clang
    #   cxx: clang++
    #   host:
    #   boost_toolset: clang
    - image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
      platform: linux/aarch64
      make_steps: depends_host monero_linux_arm64 moneroc_linux_host64
      prepare_cmd: echo ok
      prepare_cmd_depends: echo ok
      triplet: aarch64-linux-gnu
      cc: clang
      cxx: clang++
      host:
      boost_toolset: clang
    - image: alpine:3.19.1
      platform: linux/amd64
      make_steps: alpine_fix_libexecinfo depends_host monero_linux_amd64 moneroc_linux_host64
      prepare_cmd: echo ok
      prepare_cmd_depends: apk add make git curl g++ linux-headers perl libtool autoconf automake pkgconfig cmake bash bison abuild
      triplet: x86_64-alpine-linux-musl
      cc: gcc
      cxx: g++
      host:
      boost_toolset: gcc
    # - image: alpine:3.19.1
    #   platform: linux/aarch64
    #   make_steps: alpine_fix_libexecinfo depends_host monero_linux_arm64 moneroc_linux_host64
    #   prepare_cmd: echo ok
    #   prepare_cmd_depends: apk add make git curl g++ linux-headers perl libtool autoconf automake pkgconfig cmake bash bison abuild
    #   triplet: aarch64-alpine-linux-musl
    #   cc: gcc
    #   cxx: g++
    - image: git.mrcyjanek.net/mrcyjanek/sailfishos:4.5.0.18_aarch64
      platform: linux/aarch64
      make_steps: depends_host monero_linux_arm64 moneroc_linux_host64
      prepare_cmd: zypper in -y git clang libxkbcommon-devel wayland-protocols-devel wayland-client wayland-egl-devel make glibc-static byacc
      prepare_cmd_depends: make host_tool_perl
      triplet: aarch64-linux-sailfishos
      cc: clang
      cxx: clang++
      host:
      boost_toolset: clang
    - image: git.mrcyjanek.net/mrcyjanek/osxcross:14_bookworm
      platform: linux/amd64
      make_steps: depends_host monero_linux_arm64 moneroc_linux_host64
      prepare_cmd: echo ok
      prepare_cmd_depends: echo ok
      triplet: x86_64-apple-darwin23
      cc: x86_64-apple-darwin23-clang
      cxx: x86_64-apple-darwin23-clang++
      host: x86_64-apple-darwin23
      boost_toolset: clang
      openssl_target: darwin64-x86_64
labels:
  platform: ${platform}

steps:
  - name: clone repositories
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - git fetch
      - make download
  - name: build depends
    image: ${image}
    commands:
      - ${prepare_cmd}
      - ${prepare_cmd_depends}
      - CC=${cc} CXX=${cxx} HOST=${host} BOOST_TOOLSET=${boost_toolset} OPENSSL_TARGET=${openssl_target} make ${make_steps}
  - name: info
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - ls -lah libbridge/build/libwallet2_api_c.so
      - file libbridge/build/libwallet2_api_c.so
      - md5sum libbridge/build/libwallet2_api_c.so
      - sha256sum libbridge/build/libwallet2_api_c.so
      - sha512sum libbridge/build/libwallet2_api_c.so
  - name: upload artifact
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - rm -rf ~/.ssh || true
      - mkdir -p ~/.ssh
      - echo "$${SSH_PRIVKEY}" > ~/.ssh/id_rsa
      - chmod 700 ~/.ssh
      - chmod 600 ~/.ssh/id_rsa
      - xz -e libbridge/build/libwallet2_api_c.so
      - rsync --mkpath -e "ssh -o StrictHostKeyChecking=no" -raz libbridge/build/libwallet2_api_c.so.xz $${SSH_HOST}:"$${SSH_BASE_PATH}/$(git describe --tags)/$${triplet}_libwallet2_api_c.so.xz"
    secrets: [ ssh_privkey, ssh_host, ssh_base_path ]