clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false

labels:
  platform: linux/amd64

steps:
  - name: clone monero and cache depends
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - git fetch
      - git clone https://git.mrcyjanek.net/mrcyjanek/monero --recursive --depth=1 --branch=release-v0.18.3.2-legacy
      - cd monero/contrib/depends
      - make download
  - name: x86_64-linux-gnu
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - apt update
      - apt install -y gcc g++ gperf
      - ./build_single.sh x86_64-linux-gnu -j$(nproc)
  - name: i686-linux-gnu
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - apt update
      - apt install -y gcc-i686-linux-gnu g++-i686-linux-gnu gperf
      - ./build_single.sh i686-linux-gnu -j$(nproc)
  - name: aarch64-linux-gnu
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - apt update
      - apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gperf
      - ./build_single.sh aarch64-linux-gnu -j$(nproc)
  - name: x86_64-linux-android
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - apt update
      - apt install -y python-is-python3 libtinfo5 gperf
      - ./build_single.sh x86_64-linux-android -j$(nproc)
  - name: aarch64-linux-android
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - apt update
      - apt install -y python-is-python3 libtinfo5 gperf
      - ./build_single.sh aarch64-linux-android -j$(nproc)
  - name: arm-linux-androideabi
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - apt update
      - apt install -y python-is-python3 libtinfo5 gperf
      - ./build_single.sh arm-linux-androideabi -j$(nproc)
  - name: upload artifact
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - rm -rf ~/.ssh || true
      - mkdir -p ~/.ssh
      - echo "$${SSH_PRIVKEY}" > ~/.ssh/id_rsa
      - chmod 700 ~/.ssh
      - chmod 600 ~/.ssh/id_rsa
      - rsync --mkpath -e "ssh -o StrictHostKeyChecking=no" -raz release/* $${SSH_HOST}:"$${SSH_BASE_PATH}/$(git describe --tags)/"
    secrets: [ ssh_privkey, ssh_host, ssh_base_path ]