matrix:
  platform:
    - linux/amd64
    - linux/arm64

labels:
  platform: ${platform}

steps:
  - name: clone repositories
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make download
  - name: build libiconv_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make libiconv_host
  - name: build boost_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make boost_host
  - name: build zlib_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make zlib_host
  - name: build openssl_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make openssl_host
  - name: build libzmq_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make libzmq_host
  - name: build libsodium_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make libsodium_host
  - name: build libexpat_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make libexpat_host
  - name: build host_copy_libs
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make host_copy_libs
  - name: build unbound_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make unbound_host
  - name: build polyseed_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make polyseed_host
  - name: build utf8proc_host
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make utf8proc_host
  - name: build monero (amd64)
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make monero_linux_amd64
    when:
      platform: linux/amd64*
  - name: build monero (arm64)
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make monero_linux_arm64
    when:
      platform: linux/arm64*
  - name: build monero_linux_host64
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - make moneroc_linux_host64
  - name: info
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - ls -lah libbridge/build/libwallet2_api_c.so
      - file libbridge/build/libwallet2_api_c.so
      - md5sum libbridge/build/libwallet2_api_c.so
      - sha256sum libbridge/build/libwallet2_api_c.so
      - sha512sum libbridge/build/libwallet2_api_c.so
