name: compatibility check
on: [push]
jobs:
  mingw:
    strategy:
      matrix:
        coin: [monero, wownero]
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 gcc-mingw-w64-i686 g++-mingw-w64-i686
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Patch sources
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "ci@mrcyjanek.net"
          git config --global user.name "CI mrcyjanek.net"
          ./apply_patches.sh ${{ matrix.coin }}
      - name: ${{ matrix.coin }}/x86_64-w64-mingw32
        run: ./build_single.sh ${{ matrix.coin }} x86_64-w64-mingw32 -j$(nproc)
      - name: ${{ matrix.coin }}/i686-w64-mingw32
        run: ./build_single.sh ${{ matrix.coin }} i686-w64-mingw32 -j$(nproc)
      - name: rename artifacts
        run: |
          mkdir release/gh/
          for i in release/${{ matrix.coin }}/*
          do
              mv "$i" "release/gh/${{ matrix.coin }}_$(basename $i)"
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/gh/*
  android:
    strategy:
      matrix:
        coin: [monero, wownero]
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf unzip python-is-python3
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Patch sources
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "ci@mrcyjanek.net"
          git config --global user.name "CI mrcyjanek.net"
          ./apply_patches.sh ${{ matrix.coin }}
      - name: ${{ matrix.coin }}/x86_64-linux-android
        run: ./build_single.sh ${{ matrix.coin }} x86_64-linux-android -j$(nproc)
      - name: ${{ matrix.coin }}/aarch64-linux-android
        run: ./build_single.sh ${{ matrix.coin }} aarch64-linux-android -j$(nproc)
      - name: ${{ matrix.coin }}/arm-linux-androideabi
        run: ./build_single.sh ${{ matrix.coin }} arm-linux-androideabi -j$(nproc)
      - name: rename artifacts
        run: |
          mkdir release/gh/
          for i in release/${{ matrix.coin }}/*
          do
              mv "$i" "release/gh/${{ matrix.coin }}_$(basename $i)"
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/gh/*
  linux:
    strategy:
      matrix:
        coin: [monero, wownero]
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-i686-linux-gnu g++-i686-linux-gnu
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Patch sources
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "ci@mrcyjanek.net"
          git config --global user.name "CI mrcyjanek.net"
          ./apply_patches.sh ${{ matrix.coin }}
      - name: ${{ matrix.coin }}/x86_64-linux-gnu
        run: ./build_single.sh ${{ matrix.coin }} x86_64-linux-gnu -j$(nproc)
      - name: ${{ matrix.coin }}/aarch64-linux-gnu
        run: ./build_single.sh ${{ matrix.coin }} aarch64-linux-gnu -j$(nproc)
      - name: ${{ matrix.coin }}/i686-linux-gnu
        run: ./build_single.sh ${{ matrix.coin }} i686-linux-gnu -j$(nproc)
      - name: rename artifacts
        run: |
          mkdir release/gh/
          for i in release/${{ matrix.coin }}/*
          do
              mv "$i" "release/gh/${{ matrix.coin }}_$(basename $i)"
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/gh/*
  darwin:
    strategy:
      matrix:
        coin: [monero, wownero]
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf python-is-python3
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Patch sources
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "ci@mrcyjanek.net"
          git config --global user.name "CI mrcyjanek.net"
          ./apply_patches.sh monero
          ./apply_patches.sh wownero
      - name: ${{ matrix.coin }}/x86_64-apple-darwin11
        run: ./build_single.sh ${{ matrix.coin }} x86_64-apple-darwin11 -j$(nproc)
      - name: ${{ matrix.coin }}/aarch64-apple-darwin11
        run: ./build_single.sh ${{ matrix.coin }} aarch64-apple-darwin11 -j$(nproc)
      - name: rename artifacts
        run: |
          mkdir release/gh/
          for i in release/${{ matrix.coin }}/*
          do
              mv "$i" "release/gh/${{ matrix.coin }}_$(basename $i)"
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/gh/*
  macos-host:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install brew dependencies
        run: |
          brew install git unbound boost@1.76 zmq
          brew link boost@1.76
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Patch sources
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "ci@mrcyjanek.net"
          git config --global user.name "CI mrcyjanek.net"
          ./apply_patches.sh ${{ matrix.coin }}
      - name: monero/host-apple-darwin
        run: |
          ./build-single.sh ${{ matrix.coin }} host-apple-darwin -j$(sysctl -n hw.activecpu)