name: Build xmruw
run-name: Building xmruw for supported targets
on: [push]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf unzip python-is-python3 jq
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Patch sources
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "ci@mrcyjanek.net"
          git config --global user.name "CI mrcyjanek.net"
          ./apply_patches.sh monero
      - name: monero/aarch64-linux-android
        run: ./build_single.sh monero aarch64-linux-android -j$(nproc)
      - name: wownero/aarch64-linux-android
        run: ./build_single.sh wownero aarch64-linux-android -j$(nproc)
      - name: clone xmruw
        run: |
          git clone https://github.com/mrcyjanek/unnamed_monero_wallet
          cd unnamed_monero_wallet
          cp -a .fvm* ..
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: build xmruw (monero)
        run: |
          cd unnamed_monero_wallet
          ./codegen.sh -DCOIN_MONERO -DLIBSTEALTH_DISABLED
          flutter pub get
          make version
          ./build_changelog.sh
          cp ../release/monero/aarch64-linux-android_libwallet2_api_c.so.xz android/app/src/main/jniLibs/arm64-v8a/libmonero_libwallet2_api_c.so.xz
          unxz -f android/app/src/main/jniLibs/arm64-v8a/*.xz
          flutter build apk --debug --flavor clean_monero
      - name: build xmruw (wownero)
        run: |
          cd unnamed_monero_wallet
          ./codegen.sh -DCOIN_WOWNERO -DLIBSTEALTH_DISABLED
          flutter pub get
          make version
          ./build_changelog.sh
          cp ../release/wownero/aarch64-linux-android_libwallet2_api_c.so.xz android/app/src/main/jniLibs/arm64-v8a/libwownero_libwallet2_api_c.so.xz
          unxz -f android/app/src/main/jniLibs/arm64-v8a/*.xz
          flutter build apk --debug --flavor clean_wownero
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: xmruw apk
          path: unnamed_monero_wallet/build/app/outputs/flutter-apk/*.apk